<a href="https://colab.research.google.com/github/sujal290/Gen-AI/blob/main/day3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

"Suppose the IQ in a certain population is normally distributed with a mean of μ = 100 and standard deviation of σ = 15.

A researcher wants to know if a new drug affects IQ levels, so he recruits 20 patients to try it and records their IQ levels.

The following code shows how to perform a one sample z-test in Python to determine if the new drug causes a significant difference in IQ levels:"


In [ ]:
from statsmodels.stats.weightstats import ztest as ztest

#enter IQ levels for 20 patients
data = [88, 92, 94, 94, 96, 97, 97, 97, 99, 99, 105, 109, 109, 109, 110, 112, 112, 113, 114, 115]

ztest(data, value=100)
(1.5976240527147705, 0.1101266701438426)


(1.5976240527147705, 0.1101266701438426)

In [6]:
## t -test
ages=[10,20,35,50,28,40,55,18,16,55,30,25,43,18,30,28,14,24,16,17,32,35,26,27,65,18,43,23,21,20,19,70]
import numpy as np
ages_mean=np.mean(ages)
ages_mean

np.float64(30.34375)

In [7]:
sample_size=10
age_sample=np.random.choice(ages,sample_size)
age_sample



array([32, 16, 23, 20, 21, 40, 55, 18, 26, 35])

In [8]:
np.mean(age_sample)

np.float64(28.6)

In [9]:
from scipy.stats import ttest_1samp
ttest,p_value=ttest_1samp(age_sample,30)
print(p_value)

0.7231752603051921


In [10]:
 ttest,p_value=ttest_1samp(age_sample,29)
print(p_value)

0.9191177523985484


In [12]:
# Consider another example
# ages of the college students(population)
# 1 class student mean of all the ages

import numpy as np
import pandas as pd
import scipy.stats as stats
import math
np.random.seed(6)
school_ages = stats.poisson.rvs(loc=18, mu=35, size=1500)
classA_ages = stats.poisson.rvs(loc=18, mu=30, size=60)

school_ages,



(array([62, 59, 44, ..., 45, 52, 50]),)

In [13]:
classA_ages


array([52, 46, 40, 40, 47, 50, 51, 45, 44, 52, 46, 53, 43, 44, 51, 50, 54,
       42, 54, 45, 61, 53, 49, 46, 47, 41, 45, 51, 43, 45, 48, 50, 40, 52,
       44, 55, 54, 40, 45, 46, 54, 42, 46, 35, 51, 51, 46, 48, 47, 35, 52,
       52, 39, 44, 48, 40, 42, 46, 47, 45])

In [14]:
classA_ages.mean()

np.float64(46.9)

In [17]:
_,_p_value=ttest_1samp(a=classA_ages,popmean=school_ages.mean())


In [18]:
school_ages.mean()

np.float64(53.303333333333335)

In [19]:
if p_value < 0.05:
    print("We are rejecting null hypothesis")
else:
    print("We are accepting null hypothesis")

We are rejecting null hypothesis


In [20]:
import seaborn as sns
df=sns.load_dataset('iris')
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [24]:
df.corr()


ValueError: could not convert string to float: 'setosa'

In [25]:
sns.pairplot()

TypeError: pairplot() missing 1 required positional argument: 'data'